### ISSUE TITLE
Error importing selectivesearchsegmentation_opencv_custom

### ISSUE THREAD

**Issue by dumbshow** [vadimkantorov/selective_search_pytorch#2]
Hi,

I have run make according to the README instructions, with opencv directories updated to the correct locations.  It has created selectivesearchsegmentation_opencv_custom.so without displaying errors.

However, when running the following command in python, I get the following error.  Could this be a python 2/3 thing?

Thank you for sharing this helpful implementation of selective search.

----

`from opencv_custom import selectivesearchsegmentation_opencv_custom`

```
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from opencv_custom import selectivesearchsegmentation_opencv_custom

ImportError: dynamic module does not define module export function (PyInit_selectivesearchsegmentation_opencv_custom)
```

**Comment by vadimkantorov** [comment]
Maybe it somehow confuses `selectivesearchsegmentation_opencv_custom.py` and `selectivesearchsegmentation_opencv_custom.so`. Could you try placing the `.so` file elsewhere and patch the `lib_path`?

**Comment by dumbshow** [comment]
Yes, I moved it to a tmp dir and updated the lib_path, and now it loads correctly.
Did I do something wrong in the installation?
Thank you for your help.

**Comment by vadimkantorov** [comment]
No, probably my instructions were not fully tested - or maybe newer versions of Python changed some behavior. I updated the lib_path to be everywhere `selectivesearchsegmentation_opencv_custom_.so`

Thanks for reporting!
